extract = 'total_dyn_inst: (\d+)'
benchmarks = '../tools/benchmarks/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.dce]
pipeline = [
    "bril2json",
    "python3 ../first-optimizations/dce.py",
    "brili -p {args}",
]

[runs.lvn_dce]
pipeline = [
    "bril2json",
    "python3 ../first-optimizations/lvn.py",
    "python3 ../first-optimizations/dce.py",
    "brili -p {args}",
]

[runs.lvn_dce_live]
pipeline = [
    "bril2json",
    "python3 ../first-optimizations/lvn.py",
    "python3 ../first-optimizations/dce.py",
    "python3 ./live_variables.py",
    "brili -p {args}",
]