extract = 'total_dyn_inst: (\d+)'
benchmarks = '../tools/benchmarks/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.and_back]
pipeline = [
    "bril2json",
    "python3 ssa.py",
    "python3 from_ssa.py",
    "brili -p {args}",
]