extract = 'total_dyn_inst: (\d+)'
benchmarks = '../tools/benchmarks/*.bril'

[runs.baseline]
pipeline = [
    "bril2json",
    "brili -p {args}",
]

[runs.globally_unused_insts]
pipeline = [
    "bril2json",
    "python3 globally_unused_insts.py",
    "brili -p {args}",
]